version: 0.7.{build}

os: Visual Studio 2017
configuration: Release

environment:
  matrix:
    - compiler: msvc-15-seh
      build_system: cmake
      CMAKE_GENERATOR: Visual Studio 15 2017 Win64
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      MSVC_PLATFORM: amd64
      BITS: 64

    - compiler: msvc-15-seh
      build_system: cmake
      CMAKE_GENERATOR: Visual Studio 15 2017
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      MSVC_PLATFORM: x86
      BITS: 32

install:
  - cd ..
  - md deps
  # jansson
  - ps: Invoke-WebRequest "https://github.com/akheron/jansson/archive/v2.12.zip" -OutFile "jansson.zip"
  - ps: Expand-Archive jansson.zip -DestinationPath .
  - move jansson-2.12 jansson
  - cd jansson
  - md build
  - cd build
  - cmake -DJANSSON_BUILD_DOCS=OFF -DJANSSON_WITHOUT_TESTS=ON -G "%CMAKE_GENERATOR%" -DCMAKE_INSTALL_PREFIX=%APPVEYOR_BUILD_FOLDER%/deps/ ..
  - cmake --build . --config Release
  - cmake --build . --config Release --target install
  - cd ../..
  - rmdir jansson /s /q
  - del jansson.zip
  # zlib
  - ps: Invoke-WebRequest "https://github.com/madler/zlib/archive/v1.2.11.zip" -OutFile "zlib.zip"
  - ps: Expand-Archive zlib.zip -DestinationPath .
  - move zlib-1.2.11 zlib
  - cd zlib
  - md build
  - cd build
  - cmake -G "%CMAKE_GENERATOR%" -DCMAKE_INSTALL_PREFIX=%APPVEYOR_BUILD_FOLDER%/deps/ ..
  - cmake --build . --config Release
  - cmake --build . --config Release --target install
  - cd ../..
  - rmdir zlib /s /q
  - del zlib.zip
  # libpng
  - appveyor DownloadFile https://download.sourceforge.net/libpng/lpng1637.zip
  - ps: Expand-Archive lpng1637.zip -DestinationPath .
  - move lpng1637 libpng
  - cd libpng
  - md build
  - cd build
  - cmake -G "%CMAKE_GENERATOR%" -DCMAKE_INSTALL_PREFIX=%APPVEYOR_BUILD_FOLDER%/deps/ -DZLIB_LIBRARY=%APPVEYOR_BUILD_FOLDER%/deps/lib/zlib.lib -DZLIB_INCLUDE_DIR=%APPVEYOR_BUILD_FOLDER%/deps/include ..
  - cmake --build . --config Release
  - cmake --build . --config Release --target install
  - cd ../..
  - rmdir libpng /s /q
  - del lpng1637.zip
  # mxml
  - ps: Invoke-WebRequest "https://github.com/BlockoS/mxml/archive/master.zip" -OutFile "mxml.zip"
  - ps: Expand-Archive mxml.zip -DestinationPath .
  - move mxml-master mxml
  - cd mxml
  - md build
  - cd build
  - cmake -G "%CMAKE_GENERATOR%" -DCMAKE_INSTALL_PREFIX=%APPVEYOR_BUILD_FOLDER%/deps/ ..
  - cmake --build . --config Release
  - cmake --build . --config Release --target install
  - cd ../..
  - rmdir mxml /s /q
  - del mxml.zip
  # HuDK
  - cd HuDK
  - git submodule update --init --recursive

before_build:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars%BITS%.bat"
  - md package
  - md build
  - cd build 
  - cmake -G "%CMAKE_GENERATOR%" 
    -DCMAKE_INSTALL_PREFIX=../package
    -DBUILD_EXAMPLES=OFF
    -DZLIB_LIBRARY=%APPVEYOR_BUILD_FOLDER%/deps/lib/zlib.lib
    -DZLIB_INCLUDE_DIR=%APPVEYOR_BUILD_FOLDER%/deps/include
    -DPNG_PNG_INCLUDE_DIR=%APPVEYOR_BUILD_FOLDER%/deps/include
    -DPNG_LIBRARY=%APPVEYOR_BUILD_FOLDER%/deps/lib/libpng16.lib
    -DJANSSON_INCLUDE_DIR=%APPVEYOR_BUILD_FOLDER%/deps/include
    -DJANSSON_LIBRARY=%APPVEYOR_BUILD_FOLDER%/deps/lib/jansson.lib
    -DMXML_LIBRARIES=%APPVEYOR_BUILD_FOLDER%/deps/lib/mxml.lib
    -DMXML_INCLUDE_DIRS=%APPVEYOR_BUILD_FOLDER%/deps/include
    ..

build_script:
  - cmake --build . --config Release
  - cmake --build . --config Release --target install

after_build:
   - cd ../package
   - 7z a ../hudk.zip * -tzip
   
artifacts:
  - path: hudk.zip
    name: hudk-v${appveyor_build_version}-%MSVC_PLATFORM%.zip

deploy:
  release: hudk-v${appveyor_build_version}
  description: 'HuDK msvc15 %MSVC_PLATFORM% build'
  provider: GitHub
  auth_token:
    secure: xRIravp3mvMiAgogn6KGuK1yrolmSJUsum/wPXwu82bh97O7YkuQ3B178ac+WHml
  artifact: /hudk.*\.zip/
  draft: false
  prerelease: false
  on:
    branch: master
    appveyor_repo_tag: true  
  