  .bss
;;
;; ubyte: joypad
;; This array holds the values for 5 2-buttons joypad.
;;
joypad: 	.res 5, 0

;;
;; ubyte: joytrg 
;; Delta joypad values.
;;
joytrg: 	.res 5, 0

;;
;; ubyte: joyold 
;; Previous joypad values.
;;
joyold: 	.res 5, 0

;;
;; ubyte: joypad_6
;; This array contains the values for buttons III, IV, V and VI of 6 buttons
;; joypads.
;;
joypad_6: 	.res 5, 0

;; ubyte: joytrg 
;; Delta joypad values.
;;
joytrg_6: 	.res 5, 0

;;
;; ubyte: joyold 
;; Previous joypad values.
;;
joyold_6: 	.res 5, 0

