set( CMAKE_ASM_SOURCE_FILE_EXTENSIONS s;S;asm )
set( CMAKE_INCLUDE_FLAG_ASM "-I " )
set( CMAKE_ASM_COMPILE_OBJECT  "<CMAKE_ASM_COMPILER> <DEFINES> <INCLUDES> --feature bracket_as_indirect --feature string_escapes -DCA65 <FLAGS> -o <OBJECT> -v <SOURCE>" )
set( CMAKE_ASM_LINK_EXECUTABLE "<CMAKE_LINKER> <OBJECTS> -o <TARGET> <CMAKE_ASM_LINK_FLAGS> <LINK_FLAGS> <LINK_LIBRARIES>")