;;
;; Title: System variables
;;

;;
;; ushort: _bp
;; Base pointer.
_bp = $20ec
;;
;; ushort: _si
;; Source address.
_si = $20ee
;;
;; ushort: _di
;; Destination address.
_di = $20f0
;;
;; ushort: _ax
;; 
_ax = $20f8
;;
;; ushort: _al
;; _ax LSB
_al = $20f8
;;
;; ushort: _ah
;; _ax MSB
_ah = $20f9
;;
;; ushort: _bx
;; 
_bx = $20fa
;;
;; ushort: _bl
;; _bx LSB
_bl = $20fa
;;
;; ushort: _bh
;; _bx MSB
_bh = $20fb
;;
;; ushort: _cx
;; 
_cx = $20fc
;;
;; ushort: _cl
;; _cx LSB
_cl = $20fc
;;
;; ushort: _ch
;; _cx MSB
_ch = $20fd
;;
;; ushort: _dx
;;
_dx = $20fe
;;
;; ushort: _dl
;; _dx LSB
_dl = $20fe
;;
;; ushort: _dh
;; _dx MSB
_dh = $20ff

